database:
  host: 127.0.0.1:2379
target:
  mysql:
    host:
    username:
    password:
  redis:
    host: redis-15188.c91.us-east-1-3.ec2.cloud.redislabs.com:15188
    username:
    password: gOBv7mC9KVEQW7z04zARtZK5hd1j0Poe
    db: 0
  rabbitmq:
    host:
    username:
    password:
  minio:
    host:
    accesskey:
    secretkey:
